# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sysauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_rate', to='sysauth.Customer')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='DigitalWaterDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('begin_value', models.IntegerField(default=0)),
                ('begin_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('begin_year', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_water_devices', to='sysauth.Customer')),
            ],
            bases=(models.Model, main.models.WaterDeviceMixin),
        ),
        migrations.CreateModel(
            name='DigitalWaterDeviceCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='main.DigitalWaterDevice')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalWaterDeviceUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used', models.IntegerField(default=0)),
                ('collect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_of', to='main.DigitalWaterDeviceCollect')),
                ('collect_before', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_before_of', to='main.DigitalWaterDeviceCollect')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_months', to='main.DigitalWaterDevice')),
            ],
        ),
        migrations.CreateModel(
            name='IssueMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_messages', to='sysauth.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicsWaterDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('begin_value', models.IntegerField(default=0)),
                ('begin_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('begin_year', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanics_water_devices', to='sysauth.Customer')),
            ],
            bases=(models.Model, main.models.WaterDeviceMixin),
        ),
        migrations.CreateModel(
            name='MechanicsWaterDeviceCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='mechanics_water_device_collect_images')),
                ('value', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='main.MechanicsWaterDevice')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicsWaterDeviceUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used', models.IntegerField(default=0, null=True)),
                ('collect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_of', to='main.MechanicsWaterDeviceCollect')),
                ('collect_before', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_before_of', to='main.MechanicsWaterDeviceCollect')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_months', to='main.MechanicsWaterDevice')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1)),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_bills', to='sysauth.Customer')),
                ('digital_water_device_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DigitalWaterDeviceUsed')),
                ('mechanics_water_device_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MechanicsWaterDeviceUsed')),
            ],
            options={
                'ordering': ('-time__year', '-time__month'),
            },
        ),
        migrations.CreateModel(
            name='WaterPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(default=-1)),
                ('max_value', models.IntegerField(default=-1)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('min_value', 'max_value'),
            },
        ),
        migrations.CreateModel(
            name='WaterPriceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month')),
            ],
            options={
                'ordering': ('-time__month', '-time__year'),
            },
        ),
        migrations.AddField(
            model_name='waterprice',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.WaterPriceConfig'),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='price_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_bills', to='main.WaterPriceConfig'),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month'),
        ),
        migrations.AddField(
            model_name='mechanicswaterdeviceused',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month'),
        ),
        migrations.AddField(
            model_name='mechanicswaterdevicecollect',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month'),
        ),
        migrations.AddField(
            model_name='digitalwaterdeviceused',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month'),
        ),
        migrations.AddField(
            model_name='digitalwaterdevicecollect',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Month'),
        ),
    ]
