# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sysauth', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_bills', to='sysauth.Customer'),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='digital_water_device_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DigitalWaterDeviceUsed'),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='mechanics_water_device_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MechanicsWaterDeviceUsed'),
        ),
        migrations.AddField(
            model_name='mechanicswaterdeviceused',
            name='collect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_of', to='main.MechanicsWaterDeviceCollect'),
        ),
        migrations.AddField(
            model_name='mechanicswaterdeviceused',
            name='collect_before',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_before_of', to='main.MechanicsWaterDeviceCollect'),
        ),
        migrations.AddField(
            model_name='mechanicswaterdeviceused',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_months', to='main.MechanicsWaterDevice'),
        ),
        migrations.AddField(
            model_name='mechanicswaterdevicecollect',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='main.MechanicsWaterDevice'),
        ),
        migrations.AddField(
            model_name='mechanicswaterdevice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanics_water_devices', to='sysauth.Customer'),
        ),
        migrations.AddField(
            model_name='issuemessage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_messages', to='sysauth.Customer'),
        ),
        migrations.AddField(
            model_name='digitalwaterdeviceused',
            name='collect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_of', to='main.DigitalWaterDeviceCollect'),
        ),
        migrations.AddField(
            model_name='digitalwaterdeviceused',
            name='collect_before',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_before_of', to='main.DigitalWaterDeviceCollect'),
        ),
        migrations.AddField(
            model_name='digitalwaterdeviceused',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_months', to='main.DigitalWaterDevice'),
        ),
        migrations.AddField(
            model_name='digitalwaterdevicecollect',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='main.DigitalWaterDevice'),
        ),
        migrations.AddField(
            model_name='digitalwaterdevice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_water_devices', to='sysauth.Customer'),
        ),
        migrations.AddField(
            model_name='apprate',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_rate', to='sysauth.Customer'),
        ),
    ]
