# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171107_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_value', models.IntegerField(default=0)),
                ('end_value', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterPriceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('year', models.IntegerField(default=1)),
                ('default_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='waterbill',
            name='price',
        ),
        migrations.AddField(
            model_name='waterprice',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.WaterPriceConfig'),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='price_config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='water_bills', to='main.WaterPriceConfig'),
            preserve_default=False,
        ),
    ]
