# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171106_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicswaterdevice',
            name='begin_mouth',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='mechanicswaterdevice',
            name='begin_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mechanicswaterdevice',
            name='begin_year',
            field=models.IntegerField(default=1),
        ),
    ]
