# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysauth', '0001_initial'),
        ('main', '0003_auto_20171106_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_messages', to='sysauth.Customer')),
            ],
        ),
        migrations.AlterModelOptions(
            name='waterbill',
            options={'ordering': ('-year', '-mouth')},
        ),
    ]
