# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysauth', '0001_initial'),
        ('main', '0004_auto_20171106_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_rate', to='sysauth.Customer')),
            ],
        ),
    ]
