# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_apprate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apprate',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='waterbill',
            options={'ordering': ('-year', '-month')},
        ),
        migrations.RenameField(
            model_name='digitalwaterdevice',
            old_name='begin_mouth',
            new_name='begin_month',
        ),
        migrations.RenameField(
            model_name='digitalwaterdevicecollect',
            old_name='mouth',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='digitalwaterdeviceused',
            old_name='mouth',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='mechanicswaterdevice',
            old_name='begin_mouth',
            new_name='begin_month',
        ),
        migrations.RenameField(
            model_name='mechanicswaterdevicecollect',
            old_name='mouth',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='mechanicswaterdeviceused',
            old_name='mouth',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='waterbill',
            old_name='mouth',
            new_name='month',
        ),
        migrations.AlterField(
            model_name='digitalwaterdeviceused',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_months', to='main.DigitalWaterDevice'),
        ),
        migrations.AlterField(
            model_name='mechanicswaterdeviceused',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_months', to='main.MechanicsWaterDevice'),
        ),
    ]
