# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171106_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicswaterdevicecollect',
            name='image',
            field=models.ImageField(null=True, upload_to='mechanics_water_device_collect_images'),
        ),
    ]
